name: Init Terraform Backend Reusable Workflow

on:
  workflow_call:
    
    inputs:
      resourceGroupName:
        required: true
        type: string
      storageAccountName:
        required: true
        type: string
      storageAccountSku:
        required: true
        type: string
      storageAccountPublicNetworkAccess:
        required: true
        type: string
      storageAccountTier:
        required: true
        type: string
      storageAccountReplicationType:
        required: true
        type: string
      storageAccountEncryptionServices:
        required: true
        type: string
      storageAccountMinTlsVersion:
        required: true
        type: string
      terraformStateContainerName:
        required: true
        type: string
      location:
        required: true
        type: string

    secrets:
      azureClientId:
        required: true
      azureTenantId:
        required: true
      azureSubscriptionId:
        required: true


jobs:
  init-backend:
    runs-on: ubuntu-latest

    steps:

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.azureClientId }}
          tenant-id: ${{ secrets.azureTenantId }}
          subscription-id: ${{ secrets.azureSubscriptionId }}

      - name: Create Resource Group
        run: |
          set -e

          if ! az group show --name ${{ inputs.resourceGroupName }} &> /dev/null; then
            echo "Resource group ${{ inputs.resourceGroupName }} does not exist. Creating..."
            az group create --name ${{ inputs.resourceGroupName }} --location ${{ inputs.location }}
          else
            echo "Resource group ${{ inputs.resourceGroupName }} already exists."
          fi

      - name: Create Remote Backend Storage Account and Container
        run: |
          set -e
          IP=$(curl -s https://ifconfig.me)
          wait_time=25

          remove_network_rule() {
            echo "Removing network rule for IP $IP"
            az storage account network-rule remove --resource-group ${{ inputs.resourceGroupName }} --account-name ${{ inputs.storageAccountName }} --ip-address $IP
          }

          trap remove_network_rule EXIT

          if ! az storage account show --resource-group ${{ inputs.resourceGroupName }} --name ${{ inputs.storageAccountName }} > /dev/null 2>&1; then
            echo "Creating storage account ${{ inputs.storageAccountName }}..."
            az storage account create --resource-group ${{ inputs.resourceGroupName }} --name ${{ inputs.storageAccountName }} --sku ${{ inputs.storageAccountSku }} --encryption-services ${{ inputs.storageAccountEncryptionServices }} --min-tls-version ${{ inputs.storageAccountMinTlsVersion }} --location ${{ inputs.location }} --public-network-access ${{ inputs.storageAccountPublicNetworkAccess }}
            sleep $wait_time
          else
            echo "Storage account ${{ inputs.storageAccountName }} already exists."
          fi

          echo "Adding network rule for $IP"
          az storage account network-rule add --resource-group ${{ inputs.resourceGroupName }} --account-name ${{ inputs.storageAccountName }} --ip-address $IP
          sleep $wait_time

          KEY=$(az storage account keys list -g ${{ inputs.resourceGroupName }} -n ${{ inputs.storageAccountName }} --query "[0].value" -o tsv)

          if ! az storage container show --name ${{ inputs.terraformStateContainerName }} --account-name ${{ inputs.storageAccountName }} --account-key $KEY > /dev/null 2>&1; then
            az storage container create --name ${{ inputs.terraformStateContainerName }} --account-name ${{ inputs.storageAccountName }} --account-key $KEY
          fi

          az storage container show --name ${{ inputs.terraformStateContainerName }} --account-name ${{ inputs.storageAccountName }} --account-key $KEY
