apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${deployment_name}
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      nodeSelector:
         agentpool: application
      containers:
        - name: ${container_name}
          image: metabase/metabase:latest
          ports:
            - containerPort: 3000
          env:
            - name: MB_DB_TYPE
              value: "postgres"
            - name: MB_DB_HOST
              value: ${db_host}
            - name: MB_DB_DBNAME
              value: ${db_name}
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: "${secrets_name}"
                  key: MB_DB_USER
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: "${secrets_name}"
                  key: MB_DB_PASS
          resources:
            limits:
              cpu: 500m
              memory: 1Gi 