apiVersion: amlarc.azureml.com/v1alpha1
kind: InstanceType
metadata:
  name: ${name}
spec:
  nodeSelector:
    agentpool: ${agentpool}
  resources:
    requests:
      cpu: ${cpu_request}
      memory: ${memory_request}
    limits:
      cpu: ${cpu_limit}
      nvidia.com/gpu: ${gpu_limit}
      memory: ${memory_limit}