name: APIM Init Backend
on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-init-backend:
    uses: almirbanjanovic/cloud-playground-infra/.github/workflows/init.yaml@main
    with:
      baseName: ms
      environment: dev
      location: centralus
      terraformStateFileName: terraform.tfstate
      terraformStateContainerName: tfstate
      defaultStorageAccountTier: Standard
      defaultStorageAccountReplicationType: LRS
      defaultStorageAccountEncryptionServices: blob
      defaultStorageAccountMinTlsVersion: TLS1_2
      azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
      azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
      azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
