name: APIM Lab Init Backend
on: 
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

env:
  resourceGroupName: rg-apim-lab-dev-centralus
  storageAccountName: stapimlabdevcentralus
  storageAccountPublicNetworkAccess: Enabled
  storageAccountTier: Standard
  storageAccountReplicationType: LRS
  storageAccountEncryptionServices: blob
  storageAccountMinTlsVersion: TLS1_2
  terraformStateFileName: terraform.tfstate
  terraformStateContainerName: tfstate
  location: centralus

jobs:
  call-init-backend:
    uses: almirbanjanovic/cloud-playground-infra/.github/workflows/reusable-workflows/init.yaml@main
    with:
      resourceGroupName: ${{ env.resourceGroupName }}
      storageAccountName: ${{ env.storageAccountName }}
      storageAccountSku: ${{ env.storageAccountSku }}
      storageAccountPublicNetworkAccess: ${{ env.storageAccountPublicNetworkAccess }}
      storageAccountTier: ${{ env.storageAccountTier }}
      storageAccountReplicationType: ${{ env.storageAccountReplicationType }}
      storageAccountEncryptionServices: ${{ env.storageAccountEncryptionServices }}
      storageAccountMinTlsVersion: ${{ env.storageAccountMinTlsVersion }}
      terraformStateContainerName: ${{ env.terraformStateContainerName }}
      location: ${{ env.location }}
    secrets:
      azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
      azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
      azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
