name: APIM Lab Init Backend
on: 
  workflow_dispatch:
    inputs:
      resourceGroupName:
        type: string
        description: rg-apim-lab-dev-centralus
      storageAccountName:
        type: string
        description: stapimlabdevcentralus
      storageAccountPublicNetworkAccess:
        type: string
        description: Enabled
      storageAccountTier:
        type: string
        description: Standard
      storageAccountReplicationType:
        type: string
        description: LRS
      storageAccountEncryptionServices:
        type: string
        description: blob
      storageAccountMinTlsVersion:
        type: string
        description: TLS1_2
      terraformStateFileName:
        type: string
        description: terraform.tfstate
      terraformStateContainerName:
        type: string
        description: tfstate
      location:
        type: string
        description: centralus

permissions:
  id-token: write
  contents: read

jobs:
  call-init-backend:
    uses: almirbanjanovic/cloud-playground-infra/.github/workflows/reusable-workflows/init.yaml@main
    with:
      resourceGroupName: ${{ inputs.resourceGroupName }}
      storageAccountName: ${{ inputs.storageAccountName }}
      storageAccountSku: ${{ inputs.storageAccountSku }}
      storageAccountPublicNetworkAccess: ${{ inputs.storageAccountPublicNetworkAccess }}
      storageAccountTier: ${{ inputs.storageAccountTier }}
      storageAccountReplicationType: ${{ inputs.storageAccountReplicationType }}
      storageAccountEncryptionServices: ${{ inputs.storageAccountEncryptionServices }}
      storageAccountMinTlsVersion: ${{ inputs.storageAccountMinTlsVersion }}
      terraformStateContainerName: ${{ inputs.terraformStateContainerName }}
      location: ${{ inputs.location }}
    secrets:
      azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
      azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
      azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
