name: APIM Lab Init Backend
on: 
  workflow_dispatch:
    inputs:
      inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: apim-lab
        type: choice
        options:
          - apim-lab
          - my-other-project
          - demo-project

permissions:
  id-token: write
  contents: read

jobs:
  call-init-backend:
    uses: almirbanjanovic/cloud-playground-infra/.github/workflows/init.yaml@main
    with:
      environment: ${{ inputs.environment }}
    secrets:
      azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
      azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
      azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
