name: APIM Lab Init Backend
on: 
  workflow_dispatch:
    inputs:
      resourceGroupName:
        type: string
        default: rg-apim-lab-dev-centralus
      storageAccountName:
        type: string
        default: stapimlabdevcentralus
      storageAccountPublicNetworkAccess:
        type: string
        default: Enabled
      storageAccountTier:
        type: string
        default: Standard
      storageAccountReplicationType:
        type: string
        default: LRS
      storageAccountEncryptionServices:
        type: string
        default: blob
      storageAccountMinTlsVersion:
        type: string
        default: TLS1_2
      terraformStateContainerName:
        type: string
        default: tfstate
      location:
        type: string
        default: centralus

permissions:
  id-token: write
  contents: read

jobs:
  call-init-backend:
    uses: almirbanjanovic/cloud-playground-infra/.github/workflows/reusable-workflows/init.yaml@main
    with:
      resourceGroupName: ${{ inputs.resourceGroupName }}
      storageAccountName: ${{ inputs.storageAccountName }}
      storageAccountSku: ${{ inputs.storageAccountSku }}
      storageAccountPublicNetworkAccess: ${{ inputs.storageAccountPublicNetworkAccess }}
      storageAccountTier: ${{ inputs.storageAccountTier }}
      storageAccountSku: ${{ inputs.defaultStorageAccountTier }}_${{ inputs.defaultStorageAccountReplicationType }}
      storageAccountEncryptionServices: ${{ inputs.storageAccountEncryptionServices }}
      storageAccountMinTlsVersion: ${{ inputs.storageAccountMinTlsVersion }}
      terraformStateContainerName: ${{ inputs.terraformStateContainerName }}
      location: ${{ inputs.location }}
    secrets:
      azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
      azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
      azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
