# .github/workflows/main.yml
name: API Management Init Terraform Backend

on: 
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  call-init-backend:
    uses: ./.github/workflows/init.yml
    with:
      baseName: ms
      environment: dev
      location: centralus
      serviceConnectionName: my-service-connection
      terraformStateFileName: terraform.tfstate
      terraformStateContainerName: tfstate
      defaultStorageAccountTier: Standard
      defaultStorageAccountReplicationType: LRS
      defaultStorageAccountEncryptionServices: blob
      defaultStorageAccountMinTlsVersion: TLS1_2
