on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      azureClientId:
        required: true
      azureTenantId:
        required: true
      azureSubscriptionId:
        required: true


jobs:
  init-backend:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.azureClientId }}
          tenant-id: ${{ secrets.azureTenantId }}
          subscription-id: ${{ secrets.azureSubscriptionId }}

      - name: Create Resource Group
        run: |
          set -e

          if ! az group show --name ${{ vars.RESOURCE_GROUP }} &> /dev/null; then
            echo "Resource group ${{ vars.RESOURCE_GROUP }} does not exist. Creating..."
            az group create --name ${{ vars.RESOURCE_GROUP }} --location ${{ vars.LOCATION }}
          else
            echo "Resource group ${{ vars.RESOURCE_GROUP }} already exists."
          fi

      - name: Create Remote Backend Storage Account and Container
        run: |
          set -e
          IP=$(curl -s https://ifconfig.me)
          wait_time=25

          remove_network_rule() {
            echo "Removing network rule for IP $IP"
            az storage account network-rule remove --resource-group ${{ vars.RESOURCE_GROUP }} --account-name ${{ vars.STORAGE_ACCOUNT }} --ip-address $IP
          }

          trap remove_network_rule EXIT

          if ! az storage account show --resource-group ${{ vars.RESOURCE_GROUP }} --name ${{ vars.STORAGE_ACCOUNT }} > /dev/null 2>&1; then
            echo "Creating storage account ${{ vars.STORAGE_ACCOUNT }}..."
            az storage account create --resource-group ${{ vars.RESOURCE_GROUP }} --name ${{ vars.STORAGE_ACCOUNT }} --sku ${{ vars.STORAGE_ACCOUNT_SKU }} --encryption-services ${{ vars.STORAGE_ACCOUNT_ENCRYPTION_SERVICES }} --min-tls-version ${{ vars.STORAGE_ACCOUNT_MIN_TLS_VERSION }} --location ${{ vars.LOCATION }} --public-network-access ${{ vars.STORAGE_ACCOUNT_PUBLIC_NETWORK_ACCESS }}
            sleep $wait_time
          else
            echo "Storage account ${{ vars.STORAGE_ACCOUNT }} already exists."
          fi

          echo "Adding network rule for $IP"
          az storage account network-rule add --resource-group ${{ vars.RESOURCE_GROUP }} --account-name ${{ vars.STORAGE_ACCOUNT }} --ip-address $IP
          sleep $wait_time

          KEY=$(az storage account keys list -g ${{ vars.RESOURCE_GROUP }} -n ${{ vars.STORAGE_ACCOUNT }} --query "[0].value" -o tsv)

          if ! az storage container show --name ${{ vars.TERRAFORM_STATE_CONTAINER }} --account-name ${{ vars.STORAGE_ACCOUNT }} --account-key $KEY > /dev/null 2>&1; then
            az storage container create --name ${{ vars.TERRAFORM_STATE_CONTAINER }} --account-name ${{ vars.STORAGE_ACCOUNT }} --account-key $KEY
          fi

          az storage container show --name ${{ vars.TERRAFORM_STATE_CONTAINER }} --account-name ${{ vars.STORAGE_ACCOUNT }} --account-key $KEY
