name: 2. Terraform Init Remote Backend
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: apim-lab
        type: choice
        options:
          - ai-foundry
          - apim-lab

permissions:
  id-token: write
  contents: read

jobs:
  Name: Init Terraform Remote Backend
  call-init-backend:
    uses: almirbanjanovic/cloud-playground-infra/.github/workflows/init.yaml@main
    with:
      environment: ${{ inputs.environment }}
    secrets:
      azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
      azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
      azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
