on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      azureClientId:
        required: true
      azureTenantId:
        required: true
      azureSubscriptionId:
        required: true

env:
  TF_VAR_resource_group_name: ${{ vars.RESOURCE_GROUP }}

jobs: 
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}

    defaults:
        run:
          shell: bash

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Login to Azure using OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.azureClientId }}
        tenant-id: ${{ secrets.azureTenantId }}
        subscription-id: ${{ secrets.azureSubscriptionId }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Enable public access for backend storage account
      run: |
        az storage account update \
        --name ${{ vars.STORAGE_ACCOUNT }} \
        --resource-group ${{ vars.RESOURCE_GROUP }} \
        --public-network-access Enabled

        # Wait for 25 seconds
        echo "Enabling public network access and waiting for 25 seconds."
        sleep 25
        

    - name: Terraform Init
      id: init
      run: |
        terraform -chdir=${{ vars.TERRAFORM_WORKING_DIRECTORY }} init \
        -backend-config="resource_group_name=${{ vars.RESOURCE_GROUP }}" \
        -backend-config="storage_account_name=${{ vars.STORAGE_ACCOUNT }}" \
        -backend-config="container_name=${{ vars.TERRAFORM_STATE_CONTAINER }}" \
        -backend-config="key=${{ vars.TERRAFORM_STATE_BLOB }}"
      env:
        ARM_CLIENT_ID: ${{ secrets.azureClientId }}
        ARM_TENANT_ID: ${{ secrets.azureTenantId }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.azureSubscriptionId }}
        ARM_USE_OIDC: true
        ARM_USE_AZUREAD: true

    - name: Download the plan
      uses: actions/download-artifact@v4
      with:
        name: tf-plan
        path: ${{ vars.TERRAFORM_WORKING_DIRECTORY }}/

    - name: Apply the plan
      id: apply
      run: terraform -chdir=${{ vars.TERRAFORM_WORKING_DIRECTORY }} apply -auto-approve out.tfplan
      env:
        ARM_CLIENT_ID: ${{ secrets.azureClientId }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.azureSubscriptionId }}
        ARM_TENANT_ID: ${{ secrets.azureTenantId }}
        ARM_USE_OIDC: true
        ARM_USE_AZUREAD: true

    - name: Disable public access for backend storage account
      if: always()
      run: |
        az storage account update \
        --name ${{ vars.STORAGE_ACCOUNT }} \
        --resource-group ${{ vars.RESOURCE_GROUP }} \
        --public-network-access Disabled