name: 1. Test OpenID Connect
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: apim-lab
        type: choice
        options:
          - ai-foundry
          - apim-lab

permissions:
  id-token: write
  contents: read
      
jobs: 
  test-oidc:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd